import type { AIChatResult, AppLanguage, ChatMessage, ProviderKey } from '@chatbot-ai/shared';

const detectList = (input: string) =>
  input
    .toLowerCase()
    .split(/[^a-z0-9\u00c0-\u1ef9]+/i)
    .filter((item) => item.length >= 3)
    .slice(0, 6);

const normalizeTopicLabel = (input: string) =>
  input
    .trim()
    .replace(/[?！？]+$/g, '')
    .replace(/\s+là gì$/i, '')
    .replace(/\s+la gi$/i, '')
    .trim();

const buildRelatedTerms = (question: string, keywords: string[]) => {
  const topicLabel = normalizeTopicLabel(question).toLowerCase();
  const topicTokens = new Set(topicLabel.split(/\s+/).filter(Boolean));

  const filtered = keywords.filter((keyword) => !topicTokens.has(keyword.toLowerCase()));
  return filtered.slice(0, 4);
};

const languageCopy: Record<
  AppLanguage,
  {
    intro: string;
    short: string;
    detail: string;
    example: string;
    next: string;
    note: string;
  }
> = {
  vi: {
    intro:
      'Kết nối tới dịch vụ AI bên ngoài đang tạm gián đoạn, nên hệ thống sẽ dùng trợ lý học tập tích hợp sẵn để buổi học của bạn không bị ngắt quãng.',
    short: 'Giải thích ngắn gọn',
    detail: 'Phân tích theo từng lớp',
    example: 'Ví dụ hoặc cách tự kiểm tra',
    next: 'Gợi ý học tiếp',
    note:
      'Mức độ chắc chắn: trung bình. Đây là phản hồi do trợ lý học tập tích hợp sẵn tạo ra để bạn vẫn có thể tiếp tục học và demo hệ thống.',
  },
  en: {
    intro:
      'The connection to the external AI service is temporarily unavailable, so the app is using its built-in study assistant to keep your session uninterrupted.',
    short: 'Quick explanation',
    detail: 'Layered explanation',
    example: 'Example or self-check',
    next: 'Suggested next steps',
    note:
      'Confidence: medium. This response was generated by the built-in study assistant so you can continue learning and demo the system.',
  },
  bilingual: {
    intro:
      'Kết nối tới dịch vụ AI bên ngoài đang tạm gián đoạn, nên hệ thống sẽ dùng trợ lý học tập tích hợp sẵn để buổi học của bạn không bị ngắt quãng. / The connection to the external AI service is temporarily unavailable, so the app is using its built-in study assistant to keep your session uninterrupted.',
    short: 'Giải thích ngắn gọn / Quick explanation',
    detail: 'Phân tích theo từng lớp / Layered explanation',
    example: 'Ví dụ hoặc cách tự kiểm tra / Example or self-check',
    next: 'Gợi ý học tiếp / Suggested next steps',
    note:
      'Mức độ chắc chắn: trung bình. Đây là phản hồi do trợ lý học tập tích hợp sẵn tạo ra để bạn vẫn có thể tiếp tục học và demo hệ thống. / Confidence: medium. This response was generated by the built-in study assistant so you can continue learning and demo the system.',
  },
};

const buildChecklist = (question: string, keywords: string[]) => {
  const topicLabel = normalizeTopicLabel(question) || question;
  const relatedTerms = buildRelatedTerms(question, keywords);
  const items = [
    `- Định nghĩa cốt lõi của "${topicLabel}"`,
    '- Luận điểm hoặc đặc trưng quan trọng nhất của chủ đề',
    '- Ví dụ, phản biện, hoặc cách áp dụng vào bài học và bài tập',
  ];

  if (relatedTerms.length > 0) {
    items.push(`- Thuật ngữ nên hiểu thêm: ${relatedTerms.join(', ')}`);
  }

  return items.join('\n');
};

const buildFollowUpExamples = (question: string, keywords: string[]) => {
  const topicLabel = normalizeTopicLabel(question) || 'chủ đề này';
  const relatedTerms = buildRelatedTerms(question, keywords);
  const comparisonTarget = relatedTerms[0] ?? `một khái niệm liên quan đến ${topicLabel}`;

  return [
    `- Hãy giải thích **${topicLabel}** bằng ngôn ngữ đơn giản, dễ hiểu cho sinh viên mới học.`,
    `- Cho mình **một ví dụ thực tế hoặc một bài tập mẫu** về **${topicLabel}**.`,
    `- So sánh **${topicLabel}** với **${comparisonTarget}** để mình dễ phân biệt hơn.`,
  ].join('\n');
};

export const buildLocalStudyFallback = (input: {
  provider: ProviderKey;
  model: string;
  language: AppLanguage;
  messages: ChatMessage[];
  requestedProvider?: ProviderKey;
  warnings: string[];
  lastError?: unknown;
}): AIChatResult => {
  const copy = languageCopy[input.language];
  const latestUserPrompt =
    [...input.messages].reverse().find((message) => message.senderType === 'user')?.content.trim() ??
    'Chưa có nội dung câu hỏi.';
  const keywords = detectList(latestUserPrompt);
  const focus = latestUserPrompt || (keywords.length > 0 ? keywords.join(', ') : 'chủ đề chính của câu hỏi');
  const providerLabel = input.requestedProvider ?? input.provider;

  const contentMarkdown = [
    `> ${copy.intro}`,
    '',
    `## ${copy.short}`,
    `Câu hỏi hiện tại tập trung vào **${focus}**.`,
    '',
    'Bạn nên hiểu chủ đề này theo thứ tự: **định nghĩa trước, bối cảnh sau, rồi mới đến cách áp dụng và những điểm dễ nhầm lẫn**.',
    '',
    `## ${copy.detail}`,
    'Để tự học hiệu quả, hãy tách vấn đề thành 3 lớp:',
    '- **Khái niệm cốt lõi**: nó là gì, dùng để làm gì.',
    '- **Cấu trúc hoặc logic bên trong**: các thành phần, quy tắc, hoặc lập luận quan trọng.',
    '- **Ứng dụng học tập**: chủ đề này thường xuất hiện ở đâu trong bài giảng, bài tập hoặc đề thi.',
    '',
    `Với câu hỏi "${latestUserPrompt}", bạn có thể tự kiểm tra nhanh các ý sau:`,
    buildChecklist(latestUserPrompt, keywords),
    '',
    `## ${copy.example}`,
    'Bạn có thể hỏi tiếp theo các mẫu sau:',
    buildFollowUpExamples(latestUserPrompt, keywords),
    '',
    `## ${copy.next}`,
    '- Nếu cần lời giải sâu hơn, hãy cấu hình API key OpenAI hoặc Gemini rồi gửi lại câu hỏi chi tiết hơn.',
    '- Mở **Settings** để xem nhanh các tài liệu gợi ý phù hợp với chủ đề hiện tại.',
    '- Nếu đang ôn thi, hãy hỏi tiếp theo hướng: định nghĩa, ví dụ, so sánh, và bài tập vận dụng.',
    '',
    `> ${copy.note}`,
  ].join('\n');

  return {
    provider: input.provider,
    model: input.model || 'local-study-fallback',
    contentMarkdown,
    finishReason: 'stop',
    latencyMs: 0,
    fallbackUsed: true,
    warnings: [
      ...input.warnings,
      `External provider ${providerLabel} is unavailable; local study fallback was used instead.`,
      input.lastError instanceof Error ? `Last provider error: ${input.lastError.message}` : 'Last provider error unavailable.',
    ],
    confidenceNote: copy.note,
  };
};
