export const queryKeys = {
  auth: ['auth'] as const,
  sessions: ['sessions'] as const,
  archivedSessions: ['archived-sessions'] as const,
  continueLearning: ['sessions-continue-learning'] as const,
  globalSearch: (q: string) => ['global-search', q] as const,
  artifactSearch: (q: string) => ['artifact-search', q] as const,
  artifactFavorites: () => ['artifacts-favorites'] as const,
  artifactsAll: () => ['artifacts', 'all'] as const,
  messages: (sessionId: string) => ['messages', sessionId] as const,
  providers: ['providers'] as const,
  providerDiagnostics: ['providers-diagnostics'] as const,
  providerMetrics: ['providers-metrics'] as const,
  providerIncidents: ['providers-incidents'] as const,
  trainingDatasets: ['training-datasets'] as const,
  trainingExamples: (datasetId: string | null) => ['training-examples', datasetId ?? 'none'] as const,
  trainingJobs: ['training-jobs'] as const,
  evalCases: ['eval-cases'] as const,
  evalRuns: ['eval-runs'] as const,
  modelVersions: ['model-versions'] as const,
  activeModels: ['active-models'] as const,
  learningInsights: ['learning-insights'] as const,
  usage: (sessionId?: string | null) => ['chat-usage', sessionId ?? 'all'] as const,
  recommendations: (sessionId: string, query: string) =>
    ['recommendations', sessionId, query] as const,
  searchMaterials: (query: string) => ['materials-search', query] as const,
  artifacts: (sessionId: string) => ['artifacts', sessionId] as const,
};
